# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macprice', '0004_productgroup_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='priority',
            field=models.IntegerField(default=10),
        ),
    ]
