# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macprice', '0003_auto_20170202_1042'),
        ('macprice', '0005_auto_20170202_1156'),
    ]

    operations = [
    ]
