# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macprice', '0007_chat_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='cahtType',
            new_name='chatType',
        ),
    ]
