# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macprice', '0009_user_resturant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='haveChosen',
            field=models.BooleanField(default=False),
        ),
    ]
