# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macprice', '0013_product_resturant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ccal',
            field=models.IntegerField(default=0),
        ),
    ]
