# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macprice', '0014_product_ccal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastSum',
            field=models.IntegerField(default=0),
        ),
    ]
