# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macprice', '0017_auto_20170216_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgroup',
            name='average_price',
        ),
        migrations.AlterField(
            model_name='user',
            name='resturant',
            field=models.CharField(choices=[('mac', '\u041c\u0430\u043a\u0434\u043e\u043d\u0430\u043b\u044c\u0434\u0441'), ('kfc', 'KFC')], default='mac', max_length=3),
        ),
    ]
