# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('macprice', '0003_auto_20170202_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='priority',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
