# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 19:39
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('macprice', '0012_resturant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='resturant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='macprice.Resturant'),
        ),
    ]
