# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 06:47
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('macprice', '0016_productgroup_resturant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='resturant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macprice.Resturant'),
        ),
    ]
