# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 19:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('macprice', '0018_auto_20170218_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='lastRequest',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 18, 19, 8, 38, 372838, tzinfo=utc)),
        ),
    ]
