# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('macprice', '0019_chat_lastrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='lastRequest',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
